// Copyright 2018-2026 the Deno authors. MIT license.

/**
 * Don't modify this file manually.
 *
 * This file is auto-generated by the build script, modify `data.rs` instead.
 */

export const unstableIds = {
  ansi: 0,
  assert: 1,
  broadcastChannel: 3,
  bundle: 4,
  cookies: 6,
  cron: 7,
  csrf: 8,
  ffi: 10,
  formats: 11,
  fs: 12,
  glob: 13,
  hash: 14,
  html: 15,
  http: 16,
  kv: 17,
  net: 20,
  noLegacyAbort: 21,
  nodeGlobals: 22,
  otel: 24,
  parseArgs: 25,
  password: 26,
  process: 27,
  pty: 28,
  rawImports: 29,
  router: 30,
  s3: 31,
  secrets: 32,
  semver: 33,
  shell: 34,
  sqlite: 36,
  tar: 38,
  temporal: 39,
  transpile: 40,
  unsafeProto: 41,
  uuid: 42,
  vsock: 43,
  webgpu: 44,
  workerOptions: 45,
};
