// Copyright 2018-2026 the Deno authors. MIT license.

/**
 * Don't modify this file manually.
 *
 * This file is auto-generated by the build script, modify `data.rs` instead.
 */

export const unstableIds = {
  assert: 0,
  broadcastChannel: 2,
  bundle: 3,
  cron: 5,
  ffi: 7,
  formats: 8,
  fs: 9,
  glob: 10,
  hash: 11,
  http: 12,
  kv: 13,
  net: 16,
  noLegacyAbort: 17,
  nodeGlobals: 18,
  otel: 20,
  parseArgs: 21,
  password: 22,
  process: 23,
  rawImports: 24,
  router: 25,
  semver: 26,
  sqlite: 28,
  temporal: 30,
  unsafeProto: 31,
  uuid: 32,
  vsock: 33,
  webgpu: 34,
  workerOptions: 35,
};
