#!/usr/bin/env -S deno run --check --allow-write=. --allow-read=. --lock=./tools/deno.lock.json
// Copyright 2018-2026 the Deno authors. MIT license.
import { conditions, createWorkflow, step } from "jsr:@david/gagen@0.3.1";

// `deno desktop` downloads its laufey backends from a `laufey-v<version>`
// release on Done's repository instead of from upstream laufey. This workflow
// publishes that release: it fetches every archive pinned in
// `cli/laufey_sums.lock` from upstream, checks each against its pinned
// SHA-256, and uploads them. It runs whenever the lock file changes on main.
//
// The release is marked as a pre-release and never as "Latest", so
// `releases/latest` (used by `deno upgrade` and the CI delta patches) keeps
// pointing at Done's own releases. It is created with GITHUB_TOKEN, so its tag
// does not trigger the `ci` release build.
const workflow = createWorkflow({
  name: "laufey_mirror",
  on: {
    workflow_dispatch: {},
    push: {
      branches: ["main"],
      paths: ["cli/laufey_sums.lock"],
    },
  },
  concurrency: {
    group: "${{ github.workflow }}",
    cancelInProgress: false,
  },
  jobs: [{
    id: "mirror",
    name: "mirror laufey backends",
    runsOn: "ubuntu-latest",
    if: conditions.isRepository("weeabo-inc/done"),
    timeoutMinutes: 30,
    permissions: {
      contents: "write",
    },
    steps: [
      step({
        name: "Clone repository",
        uses: "actions/checkout@v6",
        with: {
          submodules: false,
        },
      }),
      step({
        name: "Mirror laufey release",
        env: {
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}",
        },
        run: [
          "set -euo pipefail",
          "version=$(sed -n 's/^# version: \\(v[0-9][0-9A-Za-z.+-]*\\)$/\\1/p' cli/laufey_sums.lock)",
          'if [[ -z "$version" ]]; then echo "cli/laufey_sums.lock has no version directive"; exit 1; fi',
          'tag="laufey-$version"',
          'is_draft=$(gh release view "$tag" --json isDraft --jq .isDraft 2>/dev/null || true)',
          'if [[ "$is_draft" == "false" ]]; then echo "$tag is already published"; exit 0; fi',
          "mkdir laufey-mirror",
          "cd laufey-mirror",
          "grep -E '^[0-9a-f]{64}  ' ../cli/laufey_sums.lock > SHA256SUMS",
          "while read -r _ file; do",
          '  curl -fsSL --retry 3 -o "$file" "https://github.com/littledivy/laufey/releases/download/$version/$file"',
          "done < SHA256SUMS",
          "sha256sum --check --strict SHA256SUMS",
          "# Upload to a draft first and publish it last, so a failed run never",
          "# leaves a published release with missing archives. A rerun resumes",
          "# from the draft.",
          'if [[ -z "$is_draft" ]]; then',
          '  gh release create "$tag" --draft --prerelease --latest=false --target "$GITHUB_SHA" \\',
          '    --title "laufey $version (mirror)" \\',
          '    --notes "Mirror of the laufey $version backend archives used by \\`deno desktop\\`, verified against cli/laufey_sums.lock."',
          "fi",
          'gh release upload "$tag" --clobber SHA256SUMS laufey-*',
          'gh release edit "$tag" --draft=false --prerelease --latest=false',
        ],
      }),
    ],
  }],
});

const header = "# GENERATED BY ./laufey_mirror.ts -- DO NOT DIRECTLY EDIT";

export function generate() {
  return workflow.toYamlString({ header });
}

export const LAUFEY_MIRROR_YML_URL = new URL(
  "./laufey_mirror.generated.yml",
  import.meta.url,
);

if (import.meta.main) {
  workflow.writeOrLint({
    filePath: LAUFEY_MIRROR_YML_URL,
    header,
  });
}
